### ISSUE TITLE
Game keep crashing

### ISSUE THREAD

**Issue by BaguDragon** [kyber-6/exploria-modpack#1]
### Describe the bug

the game crash

### Reproduction steps

i have a i5-8600K 16G Ram SSD and Geforce GTX 1070 TI

in the option i have allocated 6144Mb for the memory.

and i have put all the graphic to the lowest and it keep crashing

it started when i tried to reach a village in the jungle.

### Logs & crash-reports

https://mclo.gs/Ik0OKZk

### Mod pack version

1.20.1

**Comment by KevzCz** [comment]
were there no crash reports?
